jobs:
- name: hello-world
  plan:
  - get: bootstrap
    trigger: true
  - task: hello-world
    file: bootstrap/ci/tasks/hello.yml

resources:
- name: bootstrap
  type: git
  source:
    uri: {{git-repo}}
    branch: {{branch}}
    private_key: {{private-repo-key}}